import type { Metadata } from "next";
import { ReactNode } from "react";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { Roboto } from "next/font/google";
import { CssBaseline, ThemeProvider } from "@mui/material";
import theme from "@/theme";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import ReactQuery from "@/app/reactQuery";

const roboto = Roboto({
    weight: ["300", "400", "500", "700"],
    subsets: ["latin"],
    display: "swap",
    variable: "--font-roboto",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={roboto.variable}>
                <ReactQuery>
                    <AppRouterCacheProvider>
                        <ThemeProvider theme={theme}>
                            {process.env.NODE_ENV === "production" ? null : (
                                <ReactQueryDevtools initialIsOpen={false} />
                            )}
                            <CssBaseline />
                            {children}
                        </ThemeProvider>
                    </AppRouterCacheProvider>
                </ReactQuery>
            </body>
        </html>
    );
}
