import type { Metadata } from "next";
import { ReactNode } from "react";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { Roboto } from "next/font/google";
import { CssBaseline, ThemeProvider } from "@mui/material";
import theme from "@/theme";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import ReactQuery from "@/app/[lng]/reactQuery";
import { dir } from "i18next";

const languages = ["en", "nl"] as const;

type Language = (typeof languages)[number];

export function generateStaticParams() {
    return languages.map((lng) => ({ lng }));
}

const roboto = Roboto({
    weight: ["300", "400", "500", "700"],
    subsets: ["latin"],
    display: "swap",
    variable: "--font-roboto",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
    params,
}: Readonly<{
    children: ReactNode;
    params: Promise<{ lng: Language }>;
}>) {
    const { lng } = await params;

    return (
        <html lang={lng} dir={dir(lng)}>
            <body className={roboto.variable}>
                <ReactQuery>
                    <AppRouterCacheProvider>
                        <ThemeProvider theme={theme}>
                            {process.env.NODE_ENV === "production" ? null : (
                                <ReactQueryDevtools initialIsOpen={false} />
                            )}
                            <CssBaseline />
                            {children}
                        </ThemeProvider>
                    </AppRouterCacheProvider>
                </ReactQuery>
            </body>
        </html>
    );
}
