/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/auth'
import { Route as AppImport } from './routes/app'
import { Route as SplatImport } from './routes/$'
import { Route as AppIndexImport } from './routes/app/index'
import { Route as AuthRegisterImport } from './routes/auth/register'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AppScoreboardIndexImport } from './routes/app/scoreboard/index'
import { Route as AppScoreboardScoreboardIdImport } from './routes/app/scoreboard/$scoreboardId'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const SplatRoute = SplatImport.update({
  path: '/$',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  path: '/',
  getParentRoute: () => AppRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const AppScoreboardIndexRoute = AppScoreboardIndexImport.update({
  path: '/scoreboard/',
  getParentRoute: () => AppRoute,
} as any)

const AppScoreboardScoreboardIdRoute = AppScoreboardScoreboardIdImport.update({
  path: '/scoreboard/$scoreboardId',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof AuthImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppImport
    }
    '/app/scoreboard/$scoreboardId': {
      id: '/app/scoreboard/$scoreboardId'
      path: '/scoreboard/$scoreboardId'
      fullPath: '/app/scoreboard/$scoreboardId'
      preLoaderRoute: typeof AppScoreboardScoreboardIdImport
      parentRoute: typeof AppImport
    }
    '/app/scoreboard/': {
      id: '/app/scoreboard/'
      path: '/scoreboard'
      fullPath: '/app/scoreboard'
      preLoaderRoute: typeof AppScoreboardIndexImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppScoreboardScoreboardIdRoute: typeof AppScoreboardScoreboardIdRoute
  AppScoreboardIndexRoute: typeof AppScoreboardIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppScoreboardScoreboardIdRoute: AppScoreboardScoreboardIdRoute,
  AppScoreboardIndexRoute: AppScoreboardIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/': typeof AppIndexRoute
  '/app/scoreboard/$scoreboardId': typeof AppScoreboardScoreboardIdRoute
  '/app/scoreboard': typeof AppScoreboardIndexRoute
}

export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app': typeof AppIndexRoute
  '/app/scoreboard/$scoreboardId': typeof AppScoreboardScoreboardIdRoute
  '/app/scoreboard': typeof AppScoreboardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/$': typeof SplatRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/': typeof AppIndexRoute
  '/app/scoreboard/$scoreboardId': typeof AppScoreboardScoreboardIdRoute
  '/app/scoreboard/': typeof AppScoreboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/app'
    | '/auth'
    | '/auth/login'
    | '/auth/register'
    | '/app/'
    | '/app/scoreboard/$scoreboardId'
    | '/app/scoreboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/auth'
    | '/auth/login'
    | '/auth/register'
    | '/app'
    | '/app/scoreboard/$scoreboardId'
    | '/app/scoreboard'
  id:
    | '__root__'
    | '/$'
    | '/app'
    | '/auth'
    | '/auth/login'
    | '/auth/register'
    | '/app/'
    | '/app/scoreboard/$scoreboardId'
    | '/app/scoreboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/$",
        "/app",
        "/auth"
      ]
    },
    "/$": {
      "filePath": "$.ts"
    },
    "/app": {
      "filePath": "app.tsx",
      "children": [
        "/app/",
        "/app/scoreboard/$scoreboardId",
        "/app/scoreboard/"
      ]
    },
    "/auth": {
      "filePath": "auth.tsx",
      "children": [
        "/auth/login",
        "/auth/register"
      ]
    },
    "/auth/login": {
      "filePath": "auth/login.tsx",
      "parent": "/auth"
    },
    "/auth/register": {
      "filePath": "auth/register.tsx",
      "parent": "/auth"
    },
    "/app/": {
      "filePath": "app/index.tsx",
      "parent": "/app"
    },
    "/app/scoreboard/$scoreboardId": {
      "filePath": "app/scoreboard/$scoreboardId.tsx",
      "parent": "/app"
    },
    "/app/scoreboard/": {
      "filePath": "app/scoreboard/index.tsx",
      "parent": "/app"
    }
  }
}
ROUTE_MANIFEST_END */
